[package]
name = "S0889-construct-binary-tree-from-preorder-and-postorder-traversal"
version = "0.1.0"
authors = ["Xargin <cao1988228@163.com>"]
edition = "2018"

[dependencies]
leetcode_prelude="^0.1"
